### ISSUE TITLE
Unable to compile on Mac OS X 10.12.3

### ISSUE THREAD

**Issue by thang2410199** [skunkwerks/snappy-erlang-nif#23]
I got error while compiling snappy on Mac OS X 10.12.3, here is what I got from `./rebar compile -vvv`

> DEBUG: Rebar location: "/Users/thang2410199/Desktop/Backend/chat-dev/_build/default/lib/snappy/rebar"
> DEBUG: Evaluating config script "/Users/thang2410199/Desktop/Backend/chat-dev/_build/default/lib/snappy/rebar.config.script"
> DEBUG: Consult config file "/Users/thang2410199/Desktop/Backend/chat-dev/_build/default/lib/snappy/rebar.config"
> DEBUG: Available deps: []
> DEBUG: Missing deps  : []
> DEBUG: Predirs: []
> ==> snappy (compile)
> INFO:  sh info:
> 	cwd: "/Users/thang2410199/Desktop/Backend/chat-dev/_build/default/lib/snappy"
> 	cmd: make -C c_src
> DEBUG: 	opts: [{env,[{"REBAR_DEPS_DIR",
>                       "/Users/thang2410199/Desktop/Backend/chat-dev/_build/default/lib/snappy/deps"},
>                      {"ERL_LIBS",
>                       "/Users/thang2410199/Desktop/Backend/chat-dev/_build/default/lib/snappy/deps"},
>                      {"Apple_PubSub_Socket_Render",
>                       "/private/tmp/com.apple.launchd.6n9R8xEMuR/Render"},
>                      {"BINDIR",
>                       "/Users/thang2410199/.erlangInstaller/19.3/erts-8.3/bin"},
>                      {"CC","cc"},
>                      {"COLORFGBG","7;0"},
>                      {"COMMAND_MODE","unix2003"},
>                      {"CXX","c++"},
>                      {"DRV_CC_TEMPLATE",
>                       "cc -c $CFLAGS -g -Wall -fPIC  -I/Users/thang2410199/.erlangInstaller/19.3/lib/erl_interface-3.9.3/include -I/Users/thang2410199/.erlangInstaller/19.3/erts-8.3/include   $PORT_IN_FILES -o $PORT_OUT_FILE"},
>                      {"DRV_CFLAGS",
>                       "-g -Wall -fPIC  -I/Users/thang2410199/.erlangInstaller/19.3/lib/erl_interface-3.9.3/include -I/Users/thang2410199/.erlangInstaller/19.3/erts-8.3/include  "},
>                      {"DRV_CXX_TEMPLATE",
>                       "c++ -c $CXXFLAGS -g -Wall -fPIC  -I/Users/thang2410199/.erlangInstaller/19.3/lib/erl_interface-3.9.3/include -I/Users/thang2410199/.erlangInstaller/19.3/erts-8.3/include   $PORT_IN_FILES -o $PORT_OUT_FILE"},
>                      {"DRV_LDFLAGS",
>                       "-bundle -flat_namespace -undefined suppress  -L/Users/thang2410199/.erlangInstaller/19.3/lib/erl_interface-3.9.3/lib -lerl_interface -lei"},
>                      {"DRV_LINK_TEMPLATE",
>                       "cc $PORT_IN_FILES $LDFLAGS -bundle -flat_namespace -undefined suppress  -L/Users/thang2410199/.erlangInstaller/19.3/lib/erl_interface-3.9.3/lib -lerl_interface -lei -o $PORT_OUT_FILE"},
>                      {"EMU","beam"},
>                      {"ERLANG_ARCH","64"},
>                      {"ERLANG_TARGET","19-x86_64-apple-darwin15.6.0-64"},
>                      {"ERL_CFLAGS",
>                       " -I/Users/thang2410199/.erlangInstaller/19.3/lib/erl_interface-3.9.3/include -I/Users/thang2410199/.erlangInstaller/19.3/erts-8.3/include  "},
>                      {"ERL_EI_LIBDIR",
>                       "/Users/thang2410199/.erlangInstaller/19.3/lib/erl_interface-3.9.3/lib"},
>                      {"ERL_LDFLAGS",
>                       " -L/Users/thang2410199/.erlangInstaller/19.3/lib/erl_interface-3.9.3/lib -lerl_interface -lei"},
>                      {"EXE_CC_TEMPLATE",
>                       "cc -c $CFLAGS -g -Wall -fPIC  -I/Users/thang2410199/.erlangInstaller/19.3/lib/erl_interface-3.9.3/include -I/Users/thang2410199/.erlangInstaller/19.3/erts-8.3/include   $PORT_IN_FILES -o $PORT_OUT_FILE"},
>                      {"EXE_CFLAGS",
>                       "-g -Wall -fPIC  -I/Users/thang2410199/.erlangInstaller/19.3/lib/erl_interface-3.9.3/include -I/Users/thang2410199/.erlangInstaller/19.3/erts-8.3/include  "},
>                      {"EXE_CXX_TEMPLATE",
>                       "c++ -c $CXXFLAGS -g -Wall -fPIC  -I/Users/thang2410199/.erlangInstaller/19.3/lib/erl_interface-3.9.3/include -I/Users/thang2410199/.erlangInstaller/19.3/erts-8.3/include   $PORT_IN_FILES -o $PORT_OUT_FILE"},
>                      {"EXE_LDFLAGS",
>                       " -L/Users/thang2410199/.erlangInstaller/19.3/lib/erl_interface-3.9.3/lib -lerl_interface -lei"},
>                      {"EXE_LINK_TEMPLATE",
>                       "cc $PORT_IN_FILES $LDFLAGS  -L/Users/thang2410199/.erlangInstaller/19.3/lib/erl_interface-3.9.3/lib -lerl_interface -lei -o $PORT_OUT_FILE"},
>                      {"GEM_HOME","/Users/thang2410199/.rvm/gems/ruby-2.4.0"},
>                      {"GEM_PATH",
>                       "/Users/thang2410199/.rvm/gems/ruby-2.4.0:/Users/thang2410199/.rvm/gems/ruby-2.4.0@global"},
>                      {"HOME","/Users/thang2410199"},
>                      {"IRBRC",
>                       "/Users/thang2410199/.rvm/rubies/ruby-2.4.0/.irbrc"},
>                      {"ITERM_PROFILE","Default"},
>                      {"ITERM_SESSION_ID",
>                       "w0t0p0:DC8E167D-1506-4A5A-9150-C44833197825"},
>                      {"LANG","en_US.UTF-8"},
>                      {"LC_CTYPE","en_US.UTF-8"},
>                      {"LESS","-R"},
>                      {"LOGNAME","thang2410199"},
>                      {"LSCOLORS","Gxfxcxdxbxegedabagacad"},
>                      {"MY_RUBY_HOME",
>                       "/Users/thang2410199/.rvm/rubies/ruby-2.4.0"},
>                      {"PAGER","less"},
>                      {"PATH",
>                       "/Users/thang2410199/.erlangInstaller/19.3/erts-8.3/bin:/Users/thang2410199/.erlangInstaller/19.3/bin:/Users/thang2410199/.rvm/gems/ruby-2.4.0/bin:/Users/thang2410199/.rvm/gems/ruby-2.4.0@global/bin:/Users/thang2410199/.rvm/rubies/ruby-2.4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/thang2410199/.rvm/bin:/Users/thang2410199/.erlangInstaller/19.3/bin"},
>                      {"PROGNAME","erl"},
>                      {"PWD",
>                       "/Users/thang2410199/Desktop/Backend/chat-dev/_build/default/lib/snappy"},
>                      {"ROOTDIR","/Users/thang2410199/.erlangInstaller/19.3"},
>                      {"RUBY_VERSION","ruby-2.4.0"},
>                      {"SECURITYSESSIONID","186a7"},
>                      {"SHELL","/bin/zsh"},
>                      {"SHLVL","1"},
>                      {"SSH_AUTH_SOCK",
>                       "/private/tmp/com.apple.launchd.mLPUT9giCk/Listeners"},
>                      {"TERM","xterm-256color"},
>                      {"TERM_PROGRAM","iTerm.app"},
>                      {"TERM_PROGRAM_VERSION","3.0.15"},
>                      {"TERM_SESSION_ID",
>                       "w0t0p0:DC8E167D-1506-4A5A-9150-C44833197825"},
>                      {"TMPDIR",
>                       "/var/folders/wv/353fmbnj0fqb8kzwm_44mr0r0000gn/T/"},
>                      {"USER","thang2410199"},
>                      {"XPC_FLAGS","0x0"},
>                      {"XPC_SERVICE_NAME","0"},
>                      {"ZSH","/Users/thang2410199/.oh-my-zsh"},
>                      {"__CF_USER_TEXT_ENCODING","0x1F5:0x0:0x0"},
>                      {"_system_arch","x86_64"},
>                      {"_system_name","OSX"},
>                      {"_system_type","Darwin"},
>                      {"_system_version","10.12"},
>                      {"rvm_alias_expanded",[]},
>                      {"rvm_bin_flag",[]},
>                      {"rvm_bin_path","/Users/thang2410199/.rvm/bin"},
>                      {"rvm_docs_type",[]},
>                      {"rvm_gemstone_package_file",[]},
>                      {"rvm_gemstone_url",[]},
>                      {"rvm_hook",[]},
>                      {"rvm_niceness",[]},
>                      {"rvm_nightly_flag",[]},
>                      {"rvm_only_path_flag",[]},
>                      {"rvm_path","/Users/thang2410199/.rvm"},
>                      {"rvm_prefix","/Users/thang2410199"},
>                      {"rvm_proxy",[]},
>                      {"rvm_quiet_flag",[]},
>                      {"rvm_ruby_bits",[]},
>                      {"rvm_ruby_file",[]},
>                      {"rvm_ruby_make",[]},
>                      {"rvm_ruby_make_install",[]},
>                      {"rvm_ruby_mode",[]},
>                      {"rvm_script_name",[]},
>                      {"rvm_sdk",[]},
>                      {"rvm_silent_flag",[]},
>                      {"rvm_use_flag",[]},
>                      {"rvm_version","1.29.0 (latest)"},
>                      {"rvm_wrapper_name",[]}]},
>                {abort_on_error,"Command [compile] failed!\n"}]
> c++ -O3 -arch x86_64 -finline-functions -Wall -fPIC -I  =PROGRESS REPORT==== 6-Jun-2017::13:41:58 ===           supervisor: {local,sasl_safe_sup}              started: [{pid,<0.56.0>},                        {id,alarm_handler},                        {mfargs,{alarm_handler,start_link,[]}},                        {restart_type,permanent},                        {shutdown,2000},                        {child_type,worker}]  =PROGRESS REPORT==== 6-Jun-2017::13:41:58 ===           supervisor: {local,sasl_sup}              started: [{pid,<0.55.0>},                        {id,sasl_safe_sup},                        {mfargs,                            {supervisor,start_link,                                [{local,sasl_safe_sup},sasl,safe]}},                        {restart_type,permanent},                        {shutdown,infinity},                        {child_type,supervisor}]  =PROGRESS REPORT==== 6-Jun-2017::13:41:58 ===           supervisor: {local,sasl_sup}              started: [{pid,<0.57.0>},                        {id,release_handler},                        {mfargs,{release_handler,start_link,[]}},                        {restart_type,permanent},                        {shutdown,2000},                        {child_type,worker}]  =PROGRESS REPORT==== 6-Jun-2017::13:41:58 ===          application: sasl           started_at: nonode@nohost /Users/thang2410199/.erlangInstaller/19.3/erts-8.3/include/ -I  =PROGRESS REPORT==== 6-Jun-2017::13:41:59 ===           supervisor: {local,sasl_safe_sup}              started: [{pid,<0.56.0>},                        {id,alarm_handler},                        {mfargs,{alarm_handler,start_link,[]}},                        {restart_type,permanent},                        {shutdown,2000},                        {child_type,worker}]  =PROGRESS REPORT==== 6-Jun-2017::13:41:59 ===           supervisor: {local,sasl_sup}              started: [{pid,<0.55.0>},                        {id,sasl_safe_sup},                        {mfargs,                            {supervisor,start_link,                                [{local,sasl_safe_sup},sasl,safe]}},                        {restart_type,permanent},                        {shutdown,infinity},                        {child_type,supervisor}]  =PROGRESS REPORT==== 6-Jun-2017::13:41:59 ===           supervisor: {local,sasl_sup}              started: [{pid,<0.57.0>},                        {id,release_handler},                        {mfargs,{release_handler,start_link,[]}},                        {restart_type,permanent},                        {shutdown,2000},                        {child_type,worker}]  =PROGRESS REPORT==== 6-Jun-2017::13:41:59 ===          application: sasl           started_at: nonode@nohost /Users/thang2410199/.erlangInstaller/19.3/lib/erl_interface-3.9.3/include  -c -o /Users/thang2410199/Desktop/Backend/chat-dev/_build/default/lib/snappy/c_src/snappy/snappy-sinksource.o /Users/thang2410199/Desktop/Backend/chat-dev/_build/default/lib/snappy/c_src/snappy/snappy-sinksource.cc
> /bin/sh: 0.56.0: No such file or directory
> make: *** [/Users/thang2410199/Desktop/Backend/chat-dev/_build/default/lib/snappy/c_src/snappy/snappy-sinksource.o] Error 1
> ERROR: Command [compile] failed!

**Comment by dch** [comment]
I can't reproduce this on a reasonably vanilla OSX, if this is still present let's reopen.
