### ISSUE TITLE
Hex package

### ISSUE THREAD

**Issue by waisbrot** [skunkwerks/snappy-erlang-nif#25]
Would you be willing to publish this on [Hex](https://hex.pm/)? I'd be happy to help.

**Comment by dch** [comment]
yes, its long past time... tips welcomed. we are overdue a tag and also bumping snappy to 1.1.7, which unfortunately requires cmake build changes too.

**Comment by dch** [comment]
\o/ http://hex.pm/packages/snapperl 

`{:snappy, "~> 1.1", hex: :snapperl}` or `{snappy, "1.1.3", {pkg, snapperl}}`

PRs for bumping snappy version are welcomed.
